### PR TITLE
Read only role

### PR DESCRIPTION
**Pull request by Asergey91**
Solves GN-2536 and GN-2537

### CODE REVIEW

**Comment by Asergey91** [comment]
can both "GelinktNotuleren-schrijver" and "GelinktNotuleren-lezer" be true?

**Comment by nvdk** [comment]
I think there was a miscommunication, I'd expect this PR to make the /inbox/agendapoints view to link to read only views of the agendapoint and to protect the /agendapoints/:id/edit view so you can't access it if you don't have the necessary rights.

**Review by nvdk — CHANGES_REQUESTED** [review]
I don't think this PR quite covers the story in Jira. to be honest I think it doesn't do a lot well:
- The readonly agendapoints all list as published, even if they are not.
- You can still create agendapoints in read only mode.
- Nothing done on the /agendapoints route

I believe we discussed the scope of the story quite well during the planning session, please pay more attention next time.

**Comment by Asergey91** [comment]
my bad, oscar will be taking over

**Pull request merged**
