### PR TITLE
GN-4264: enable template comments in GN

### PR DESCRIPTION
**Pull request by abeforgit**
### Overview

bumps plugins to 10.0.0
updates config to reflect the interface changes
removes outdated references to templateVariablePlugin from environment.js
enables template-comments-plugin on both editor configs

##### connected issues and PRs:

[GN-4264](https://binnenland.atlassian.net/browse/GN-4264)

### Setup

just run it

### How to test/reproduce

check template plugin, and variable plugins
### Checks PR readiness
- [ ] UI: works on smaller screen sizes
- [ ] UI: feedback for any loading/error states
- [ ] Check cancel/go-back flows
- [ ] Check database state correct when deleting/updating (especially regarding relationships)
- [ ] changelog
- [x] npm lint
- [ ] no new deprecations

### CODE REVIEW

**Comment by x-m-el** [comment]
Probably want to "wait" on [PR to hide template comments when publishing](https://github.com/lblod/notulen-prepublish-service/pull/105) before merging this? So we don't get template comments in published data.

Both [PR for hiding template comments in frontend GN](https://github.com/lblod/frontend-gelinkt-notuleren/pull/545) and here template comments are added to editor, so will need to look out for at merging.

Is there any clear indication if we want template comments to be insertable in GN, like in agendapoints? Because I'd think there isn't more example/info to be given at this stage. Or are they meant as any general "extra information" (so an actual _comment_ :p ), to give some information about what to do in a certain agenda point?

Note that at this point they are hidden when previewing an agenda and are only shown during editing. So as far as I can see, the use would only be if an agenda point is created/edited in multiple stages and not at once.

**Review by x-m-el — CHANGES_REQUESTED** [review]
still have to import `@import "template-comments-plugin";` in app styles (app.scss). Note: was missing from documentation to add this, this is added in a PR for template comment readme update.

For the rest is good. Tested comments and variables in agenda and regulatory statement :+1:

**Comment by abeforgit** [comment]
Yeah I considered waiting, but given that the corresponding feature is already active on GN QA, if templates containing them will be used now in GN they will simply render as flat text, which I though was about as bad as them showing up in publications, but this at least can get the testers going

I was also debating whether or not GN users had to be able to insert them or not, figured why not. From what I gather the "edit in multiple stages" workflow is a real usecase, and a finished regulation/agenda item can be completed by different people. 

And on principle I want to move away from these "if I delete this, I can't put it back" scenarios where its there in the template, but the GN user lacks the tools to make that "thing" they see. They can already edit the comments anyway, which I'm completely fine with as well.

Hidden on preview is also perfect imo, the reader never needs to see them, only the person editing the document should.

And thanks for the hint about the css, I almost made a ticket for cleaning up the styling :see_no_evil:

**Comment by abeforgit** [comment]
> so will need to look out for at merging

merge conflicts are like spiders: they're more afraid of you than you are of them

**Pull request merged**
