### PR TITLE
Made attachments pill clickable and go to the uploading part of the behandeling

### PR DESCRIPTION
**Pull request by lagartoverde**
Solves https://binnenland.atlassian.net/browse/GN-3342

### CODE REVIEW

**Comment by Dietr** [comment]
Replaced the nested link by the new pill component. This way the whole pill is clickable.

**Review by Dietr — APPROVED** [review]

**Review by nvdk — CHANGES_REQUESTED** [review]
Looks like some changes are required, I think the linter is warning about an actual syntax error.
@lagartoverde can you have a look?

**Comment by lagartoverde** [comment]
Weird that it complained as it wasn't on local, but it should be fixed now :)

**Review by Asergey91 — APPROVED** [review]

**Comment by nvdk** [comment]
Can someone pick up fixing the merge conflict?

**Pull request merged**
