### PR TITLE
Bugfix/problem with title in dev

### PR DESCRIPTION
**Pull request by lagartoverde**
In the end the problem with the title spotted by Kevin was indeed happening, but only in production with a Chrome browser, this solves it, basically the function toggle active was changing the active value of the component multiple times in the same computation because of the focus out event.

### CODE REVIEW

**Review by x-m-el — COMMENTED** [review]
this code feels overly complex for what it does. If I see correctly:
`toggleActive` only gets used in template if active is false (=> should always set it to true)
in the code it always gets set (never toggled).

So toggleActive could be changed to 
```
setActive(val) {
  if (this.active && !this.title) {
      this.error = true;
    } else {
      this.active = val;
    }
}
```

**Comment by x-m-el** [comment]
> > this code feels overly complex for what it does. If I see correctly: `toggleActive` only gets used in template if active is false (=> should always set it to true) in the code it always gets set (never toggled).
> > So toggleActive could be changed to
> > ```
> > setActive(val) {
> >   if (this.active && !this.title) {
> >       this.error = true;
> >     } else {
> >       this.active = val;
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > With then also a change in the template to `{{on "click" (fn this.setActive true)}}`
> 
> Basically the problem is that if this.active is true it shouldn't be set to true again, because that causes some problems, I have now divided it into 2 functions so I can do the checks better, yesterday was too focus on making it work that I forgot to make it good :). Your solution is very similar to the one it was already there, the problem is that this.setActive(false) is called twice in the same computation and then it causes problems if you modify the this.active that your function does. Another solution would be to avoid the second call to the toggleActive but is called on a focusout event that I don't really know how to avoid

Wait, so setting isActive twice to the same value creates the problem? I wouldn't have guessed with the code :p
Wouldn't it then be nicer to solve this with [dedupeTracked](https://github.com/tracked-tools/tracked-toolbox#dedupetracked) then?
I think that function is meant for cases like this and it would avoid the extra checks and extra need for functions i think.

**Comment by lagartoverde** [comment]
Tried with deduped tracked and the old code but the same error still appears

**Review by x-m-el — COMMENTED** [review]
add a comment why the weird code is needed, so people don't refactor it away in the future and reintroduce the bug. If it's too hard to explain you could add a link to this PR (but that's often less clean). Then it can be merged :)

**Review by x-m-el — APPROVED** [review]

**Pull request merged**
