### PR TITLE
Feature/get draft description

### PR DESCRIPTION
**Pull request by lagartoverde**
Get description of the draft agendapoint when selecting it

### CODE REVIEW

**Comment by lagartoverde** [comment]
Sorry, I converted to a draft because I reread the issue and it should be a button not automatic

**Comment by lagartoverde** [comment]
Ready for review now :)

**Comment by Asergey91** [comment]
hm couldn't get it to work with a fresh document with only the description filled in and nothing else.

**Comment by lagartoverde** [comment]
Realized that this was not consistent because it was missing the prefixes for marawa to work 100% correct, now it should work every time

**Review by nvdk — APPROVED** [review]
looks good and works ok! 

if there's no description the behaviour feels a bit wonky, in that the user doesn't have any feedback what so ever. 

perhaps some kind of message if we don't find a description would be nice, or a loading bar while processing so users know something is happening?

**Comment by lagartoverde** [comment]
Sorry, I forgot about this, I tried adding a loading bar but the function returns instantly, maybe a message would be nice, but not sure where to put it, @Dietr do you have something to say about this? :)

**Pull request merged**
