### PR TITLE
make static TOC look the same in dynamic content

### PR DESCRIPTION
**Pull request by usrtim**
Needed for: https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/135

### CODE REVIEW

**Comment by usrtim** [comment]
@abeforgit based on your comments here: https://github.com/lblod/ember-rdfa-editor-lblod-plugins/pull/135 , I move the tableOfContentsRange and the onUpdate logic to GN, and run it when we save the document. I'm afraid we are introducing a new  issue here because I'm constantly getting  the message that changes aren't saved(the popup message)

**Review by lagartoverde — APPROVED** [review]

**Comment by abeforgit** [comment]
fyi added this ticket, but it's not a blocker for this pr: https://binnenland.atlassian.net/browse/GN-4307

**Review by abeforgit — CHANGES_REQUESTED** [review]
toggling the ToC after saving does not show "unsaved changes" in the UI, but it does (correctly, cause something has changed) trigger the alert. would be nice to get them in sync. Otherwise this is good to go (once the dependent pr has been merged)

**Comment by abeforgit** [comment]
https://github.com/lblod/ember-rdfa-editor-lblod-plugins/releases/tag/v6.1.0 is released, so you can update the `package.json`

**Comment by lagartoverde** [comment]
> toggling the ToC after saving does not show "unsaved changes" in the UI, but it does (correctly, cause something has changed) trigger the alert. would be nice to get them in sync. Otherwise this is good to go (once the dependent pr has been merged)

This functionality was not enabled on regulatory statements, I enabled it now

**Pull request merged**
