### PR TITLE
Feature/publication validation

### PR DESCRIPTION
**Pull request by lagartoverde**

### CODE REVIEW

**Comment by lagartoverde** [comment]
Still need some style review from @Dietr :)

**Comment by nvdk** [comment]
@lagartoverde I ran into the following error when trying to publish:

```
TypeError: this.notulen is undefined
get zittingWrapper notulen.js:100
    Ember 2
        getPossibleMandatoryProxyValue
```

**Comment by lagartoverde** [comment]
Did you do anything special? I'm not getting that error

**Comment by nvdk** [comment]
I'm trying to publish a meeting with 2 agendapoints, each agendapoint has a decision. one is made public, the other isn't. the preimporter says
```
preimporter_1                  | Creating a new versioned notulen for http://data.lblod.info/id/zittingen/608033D32476B4000A000008
preimporter_1                  | {}
``` 
and returns a 400 bad request

**Comment by nvdk** [comment]
> I'm trying to publish a meeting with 2 agendapoints, each agendapoint has a decision. one is made public, the other isn't. the preimporter says
> 
> ```
> preimporter_1                  | Creating a new versioned notulen for http://data.lblod.info/id/zittingen/608033D32476B4000A000008
> preimporter_1                  | {}
> ```
> 
> and returns a 400 bad request

ah I believe one of the decision may have already been published as an extract as well!

**Comment by nvdk** [comment]
was looking at the wrong branch of the prepublisher :facepalm:

**Comment by nvdk** [comment]
@Dietr FYI I've deployed the necessary backend changes so you can review this as well.

**Review by Dietr — APPROVED** [review]

**Review by nvdk — APPROVED** [review]

**Pull request merged**
