### PR TITLE
Feature/agendapunt ordering

### PR DESCRIPTION
**Pull request by Asergey91**
stuff seems to be mostly tested and working

### CODE REVIEW

**Comment by nvdk** [comment]
@Asergey91 this is marked as in draft, could you indicate what's already ready for review and what isn't?

**Comment by Asergey91** [comment]
I need help with the saveAll function in modal.js everything else seems ok to me @nvdk

**Comment by Asergey91** [comment]
also updated the backend in the branch of the same name, required to work properly

**Comment by abeforgit** [comment]
superseded by #27

**Pull request closed without merging**
