### PR TITLE
Update models and relationships

### PR DESCRIPTION
**Pull request by elpoelma**
This PR includes a complete revisal/update of all ember-data models. It includes the removal of models and relationships, the addition of missing models and relationships and ensuring the `inverse` field is always explicitly set (in prepreration for https://github.com/emberjs/data/pull/8115).
Specifically, it includes the removal of the following ember-data models:
- `task-solution`
- `task`
- `tasklist-solution`
- `tasklist`
- `versioned-agenda`

And the removal of the following relationships:
- `realisatie` from `besluit`
- `versioned-agendas`, `versioned-notulen`, `versioned-besluiten-lijsten` and `versioned-behandelingen` from `document-container`
- replaced `versioned-agenda` model type by `agenda` in `published-resource`
- replaced `versioned-agenda` model type by `agenda` in `signed-resource`

The addition of the following models:
- `beleidsdomein-code`
- `lidmaatschap`
- `lijsttype`
- `tijdsinterval`
- `werkingsgebied`

Additionally, this PR also introduces spacing in some models to make them clearer and more readable.
To be tested in combination with https://github.com/lblod/app-gelinkt-notuleren/pull/156

### CODE REVIEW

**Review by nvdk — APPROVED** [review]
looks good to me :+1:

**Review by lagartoverde — APPROVED** [review]
Looks good to me

**Review by abeforgit — CHANGES_REQUESTED** [review]
getting the same error as here:
https://github.com/lblod/frontend-gelinkt-notuleren/pull/431#pullrequestreview-1441777810

**Comment by elpoelma** [comment]
> getting the same error as here: [#431 (review)](https://github.com/lblod/frontend-gelinkt-notuleren/pull/431#pullrequestreview-1441777810)

Aha ok, should be fixed now. The issue was that when I reset the inverses to `null` for some models which had their inverse as `null` before, I forgot to check if the other side of the relationship also had inverse: `null`. That should be fixed now, I rechecked all inverses and don't see anymore issues with the meeting page.

**Pull request merged**
