### PR TITLE
bump template and decision type plugin

### PR DESCRIPTION
**Pull request by nvdk**
bumps editor to 0.50.0 and moves the template and decision plugin to the latest versions. updated to the new plugin wiring in GN.

edit: as mentioned in the chat  I think it's odd for users that the "voeg sjabloon toe" button dissapears while typing, might be better to disable it

### CODE REVIEW

**Comment by nvdk** [comment]
Hmm yes that's the old way of calling the plugin (the legt one). This is fixed in https://github.com/lblod/ember-rdfa-editor/pull/232 . perhaps it's best to convert this to a draft until that's merged

**Review by abeforgit — APPROVED** [review]
Bit weird that this pr also includes a release? but looks fine otherwise

**Comment by nvdk** [comment]
> Bit weird that this pr also includes a release? but looks fine otherwise

hmm yes, probably because I branched of master and we don't have the habit of merging the releases back into dev

**Review by benjay10 — APPROVED** [review]

**Comment by nvdk** [comment]
rebased on latest dev

**Pull request merged**
