### PR TITLE
Feature/file upload

### PR DESCRIPTION
**Pull request by Asergey91**
Didn't have time to do some things

- [x] add translations 

- [x] enable more than 20 attachments

- [ ] make download links work on dev, should work if deployed though (I think)...

- [x] fix linting errors

### CODE REVIEW

**Comment by Asergey91** [comment]
ok a bunch of bugs are happening already 

editing a document then changing view to attachments undoes changes to document

- [ ] fix it

**Comment by Asergey91** [comment]
- [ ] adapt to changes to backend

**Comment by nvdk** [comment]
for what it's worth you can always check if it works deployed by replacing http://localhost:4200 with http://localhost:80/ and check if it works :)

**Comment by Asergey91** [comment]
ok couldn't figure out how to get the dl links to work locally, but its not a priority, ready for review

**Review by lagartoverde — APPROVED** [review]
Looks good, to be nitpick the loading of a document when you upload it's a little bit weird, and the changes on the attachments are saved even if the document is not, not sure if that's on purpose

**Pull request merged**
