### PR TITLE
remove vo-webuniversum

### PR DESCRIPTION
**Pull request by nvdk**
keeps track of the work to be done to remove vo-webuniversum

* [x] [lblod/ember-rdfa-editor-date-overwrite-plugin](/lblod/ember-rdfa-editor-date-overwrite-plugin)@0.3.3 depends on vo-webuniversum (bump or remove)
* [x] [lblod/ember-rdfa-editor-date-plugin](/[lblod/ember-rdfa-editor-date-plugin)@0.9.0 depends on vo-webuniversum (bump or remove)
* [x] [lblod/ember-rdfa-editor-import-snippet-plugin](/lblod/ember-rdfa-editor-import-snippet-plugin)@0.7.3  depends on vo-webuniversum (bump or remove)
* [x] [lblod/ember-rdfa-editor-citaten-plugin](/lblod/ember-rdfa-editor-citaten-plugin)@0.12.0  depends on vo-webuniversum (bump or remove)
* [x] l[blod/ember-rdfa-editor-standard-template-plugin ](/lblod/ember-rdfa-editor-standard-template-plugin ) depends on vo-webuniversum (bump or remove)
* [x] replace wu-datepicker with equivalent from appuniversum
* [x] remove old routes depending on vo-webuniversum
* [x] remove usage of WuButton and WuButtonGroup from besluit-type-plugin
* [x] remove usage of WuButton in acm-idm login
* [x] use say styles in the template plugin
* [x] import route modal is no longer styled correctly
* [ ] replace ember-vo-file-upload with au equivalent
will add other tasks as I encounter them

### CODE REVIEW

**Comment by nvdk** [comment]
wu-datepicker should be addressed with **https://github.com/lblod/frontend-gelinkt-notuleren/pull/89**

**Comment by nvdk** [comment]
see https://github.com/lblod/ember-rdfa-editor-besluit-type-plugin/pull/7

**Review by Dietr — COMMENTED** [review]
I'm having some trouble to test and review this as AcmIdm seems to trow an error.
Old version is missing the WuButton component. The new/refactored version says this `Error: Could not find module `@ember/component` imported from `@lblod/ember-acmidm-login/components/acmidm-login`

**Comment by nvdk** [comment]
> I'm having some trouble to test and review this as AcmIdm seems to trow an error.
> Old version is missing the WuButton component. The new/refactored version says this `Error: Could not find module `@ember/component`imported from`@lblod/ember-acmidm-login/components/acmidm-login`

erika figured out the cause in https://github.com/lblod/ember-acmidm-login/pull/4#issuecomment-907618192 . I'll release the addon shortly and bump it here so you can test. If I read the issue correctly that should work :).

**Comment by lagartoverde** [comment]
remove usage of WuButton in acm-idm login -> done on https://github.com/lblod/ember-acmidm-login/pull/4
use say styles in the template plugin -> in review https://github.com/lblod/ember-rdfa-editor-standard-template-plugin/pull/4 (need linting fixes)

**Comment by nvdk** [comment]
file uploader available in https://github.com/appuniversum/ember-appuniversum/pull/139

**Comment by nvdk** [comment]
@Dietr can you have a look at https://github.com/lblod/frontend-gelinkt-notuleren/pull/86/commits/0dc6d0ef65ce439bcc0961435de34cac36864f56 ? 

To trigger the popup, first log into GN and then go to http://localhost:4200/import/new?omitCredentials=true&source=https://dev.kleinbord.lblod.info/snippets/example-opstellingen.html&mock=true

**Comment by nvdk** [comment]
In the hope to progress on this PR, I would not wait for the replacement of the vo-file-upload component.

**Pull request merged**
